---
title: "Gulf War Crisis"
date: 'August 1990 - February 1991'

runtime: shiny
---

<style type="text/css">
  body{
  font-family: Helvetica;
  font-size: 12pt;
  margin: 50px;
}
</style>

```{r setup, include=FALSE}
library(magrittr)
library(shiny)
library(ggplot2)
library(DT)
library(kableExtra)
library(RColorBrewer)
library(tidyverse)
library(scales)
library(dplyr)
library(igraph)
library(ggraph)
library(visNetwork)
library(xaringan)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
```

## Background Information:
A short paragraph on the crisis to be written by one of the ITL-ers, which includes background and any relevent votes, bills, etc. 

## Relevent Data:
```{r, warning = FALSE}
library(googlesheets4)

Sheet  <- read_sheet("https://docs.google.com/spreadsheets/d/1jx9-rlPCkUw-gJvTQValRG84TKs4vQ60uNrmpm-XQ9U/edit?usp=sharing")


library(stringr)
Sheet$House <- str_sub(Sheet$MasterID,-4,-4)
Sheet$Party <- str_sub(Sheet$MasterID,-7,-5)
Sheet$Party <- ifelse(Sheet$Party == "SBI", 100, Sheet$Party )
Sheet$HouseParty <- paste(Sheet$House, Sheet$Party)


Sheet$HouseParty <- ifelse(Sheet$HouseParty == "H 100", "House Democrat", Sheet$HouseParty)
Sheet$HouseParty <- ifelse(Sheet$HouseParty == "S 100", "Senate Democrat", Sheet$HouseParty)
Sheet$HouseParty <- ifelse(Sheet$HouseParty == "H 200", "House Republican", Sheet$HouseParty)
Sheet$HouseParty <- ifelse(Sheet$HouseParty == "S 200", "Senate Republican", Sheet$HouseParty)


Sheet$Irrelevant <- as.character(Sheet$Irrelevant)

Sheet <- subset(Sheet, Sheet$Irrelevant == "NA")


Sheet$Advocates_for_Use_of_American_Military_Force <- as.character(Sheet$Advocates_for_Use_of_American_Military_Force)
Sheet$Advocates_against_Use_of_American_Military_Force <- as.character(Sheet$Advocates_against_Use_of_American_Military_Force)

Sheet <- subset(Sheet, Sheet$Advocates_for_Use_of_American_Military_Force == 1 | Sheet$Advocates_against_Use_of_American_Military_Force == 1)


Sheet$date<-as.Date(as.character(Sheet$date),format="%Y%m%d")

Sheet$HD <- ifelse(Sheet$Advocates_for_Use_of_American_Military_Force == "NA",0,1)


Sheet$HD <- ifelse(Sheet$HD == 1,"Support Force","Oppose Force")

downloadHandler(
  filename = function() { 
    paste("Iraq_1990_Gulf_War",".csv", sep = "")
  }, 
  content = function(file) {
    write.csv(Sheet, file)
  },
  outputArgs = list(label = "Iraq_1990_Gulf_War (.csv) ")
)

```

## Plot on Use of Force:

```{r, warning = FALSE}

ggplot(Sheet, aes(date, HD)) +  geom_jitter(aes(colour = HouseParty),width = 2, height = 0.3, size = 3, alpha = .6)  + ggtitle("Gulf War 1990") +  
xlab("Date") + # for the x axis label
ylab("Sentiment") +
    geom_text(
    label="Sarin Attack",
    x=as.Date('2013-08-21'), angle = 90,hjust = -0, size = 2.4, vjust = 0)+
    geom_text(
    label="Obama Requests AUMF",
    x=as.Date('2013-08-31'), angle = 90,hjust = 0.4, size = 2.4, vjust = 0)+ scale_color_manual(values = c("House Democrat" = "dodgerblue2", "House Republican"="red",
                                "Senate Democrat" = "dark blue", "Senate Republican" = "firebrick4")) 

```
