---
title: "India - Pakistan Nuclear Test Crisis (425)"
author: "ICB Crisis No. 425"
date: "February 1998 - June 1998"
output: html_document
runtime: shiny
---
  
```{r setup, include=FALSE}
## firstly add all necessary packages, in order for the document to run, the packages must be first installed via the console unless you already have them in your RStudio, use "install_packages" as the command in the console
library(shiny)
library(ggplot2)
library(DT)
library(kableExtra)
library(tidyverse)
library(dplyr)
library(googlesheets4)
library(stringr)


## second require the knit function to be "knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)" in order for all output to go from Rmarkdown to HTML
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
```

## Background Information:
#### Gurman's mini paragraph...

## Relevent Data:
```{r, warning = FALSE}

## add in the parenthesis of the read_sheet function the link of the Google sheet
## don't use the shared link, use the direct http link from chrome

Sheet  <- read_sheet("https://docs.google.com/spreadsheets/d/1mtVhHENgYyFaApb914Cc2R_KD3SuoME0ScAxW_oQTRE/edit#gid=1276040235")

## data cleaning and subset below, functions for all sheets
Sheet$House <- str_sub(Sheet$MasterID,-4,-4)
Sheet$Party <- str_sub(Sheet$MasterID,-7,-5)
Sheet$Party <- ifelse(Sheet$Party == "SBI", 100, Sheet$Party )
Sheet$HouseParty <- paste(Sheet$House, Sheet$Party)

Sheet$HouseParty <- ifelse(Sheet$HouseParty == "H 100", "House Democrat", Sheet$HouseParty)
Sheet$HouseParty <- ifelse(Sheet$HouseParty == "S 100", "Senate Democrat", Sheet$HouseParty)
Sheet$HouseParty <- ifelse(Sheet$HouseParty == "H 200", "House Republican", Sheet$HouseParty)
Sheet$HouseParty <- ifelse(Sheet$HouseParty == "S 200", "Senate Republican", Sheet$HouseParty)

Sheet$Irrelevant <- as.character(Sheet$Irrelevant)

Sheet <- subset(Sheet, Sheet$Irrelevant == "NA")

Sheet$Advocates_for_Use_of_American_Military_Force <- as.character(Sheet$Advocates_for_Use_of_American_Military_Force)
Sheet$Advocates_against_Use_of_American_Military_Force <- as.character(Sheet$Advocates_against_Use_of_American_Military_Force)

Sheet <- subset(Sheet, Sheet$Advocates_for_Use_of_American_Military_Force == 1 | Sheet$Advocates_against_Use_of_American_Military_Force == 1)


Sheet$date<-as.Date(as.character(Sheet$date),format="%Y%m%d")

Sheet$HD <- ifelse(Sheet$Advocates_for_Use_of_American_Military_Force == "NA",0,1)


Sheet$HD <- ifelse(Sheet$HD == 1,"Support Force","Oppose Force")

## shiny button function below for csv download
## change the title of the csv file paste 
## this is being funky right now so if it doesn't work no stress
downloadHandler(
  filename = function() { 
    paste("Iraq_1990_Gulf_War",".csv", sep = "")
  }, 
  content = function(file) {
    write.csv(Sheet, file)
  },
  outputArgs = list(label = "Iraq_1990_Gulf_War (.csv) ")
)
```

## Plot on Use of Force:

```{r, warning = FALSE}

## this code subsets all the aggregate data for the trend line, all you have to do to retrieve the trend line for your crisis is change the crisno == "440" value to whatever crisis number the new crisis has
trend_sheet  <- read_sheet("https://docs.google.com/spreadsheets/d/1s1tsOtG2CcIrLPN7RxT-QRY7vNiYFy8SMA3tbGk_PpI/edit#gid=1633578064")
crisis_trend <- subset(trend_sheet,crisno == "425")

## remember to change the ggtitle to the title of the crisis and dates
ggplot(Sheet, aes(date, HD)) +  geom_jitter(aes(colour = HouseParty),width = 2, height = 0.3, size = 3, alpha = .6)  + ggtitle("Gulf War Crisis (August 1990 - February 1991)") +  
  xlab("Date") + ylab("Sentiment") + scale_color_manual(values = c("House Democrat" = "dodgerblue2", "House Republican"="red", "Senate Democrat" = "dark blue", "Senate Republican" = "firebrick4")) + geom_line(data=crisis_trend, aes(x= as.Date(speech_cutoff_date), y = avg_agg_support))
```